spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sdcinfo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 852456Z666
server:
  port: 8081
  servlet:
    context-path: /Backend
mybatis:
  mapper-locations: com/ccd/backend/mapper/*.xml
logging:
  level:
    com:
      ccd:
        backend:
        mapper: debug
